// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.5.1
// source: github.com/yincongcyincong/BasicStudy/proto/api/test/mgetStudyTestByIDs.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MgetStudyTestByIDsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []uint64 `protobuf:"varint,1,rep,name=ids" json:"ids,omitempty"` // id
}

func (x *MgetStudyTestByIDsReq) Reset() {
	*x = MgetStudyTestByIDsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MgetStudyTestByIDsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MgetStudyTestByIDsReq) ProtoMessage() {}

func (x *MgetStudyTestByIDsReq) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MgetStudyTestByIDsReq.ProtoReflect.Descriptor instead.
func (*MgetStudyTestByIDsReq) Descriptor() ([]byte, []int) {
	return file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_rawDescGZIP(), []int{0}
}

func (x *MgetStudyTestByIDsReq) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type MgetStudyTestByIDsData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info map[uint64]*StudyTest `protobuf:"bytes,1,rep,name=info" json:"info,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // information
}

func (x *MgetStudyTestByIDsData) Reset() {
	*x = MgetStudyTestByIDsData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MgetStudyTestByIDsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MgetStudyTestByIDsData) ProtoMessage() {}

func (x *MgetStudyTestByIDsData) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MgetStudyTestByIDsData.ProtoReflect.Descriptor instead.
func (*MgetStudyTestByIDsData) Descriptor() ([]byte, []int) {
	return file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_rawDescGZIP(), []int{1}
}

func (x *MgetStudyTestByIDsData) GetInfo() map[uint64]*StudyTest {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto protoreflect.FileDescriptor

var file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_rawDesc = []byte{
	0x0a, 0x4d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x69, 0x6e,
	0x63, 0x6f, 0x6e, 0x67, 0x63, 0x79, 0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x67, 0x2f, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x53, 0x74, 0x75, 0x64, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x6d, 0x67, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x79,
	0x54, 0x65, 0x73, 0x74, 0x42, 0x79, 0x49, 0x44, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x73, 0x74, 0x75, 0x64, 0x79, 0x1a, 0x41, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x67,
	0x63, 0x79, 0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x67, 0x2f, 0x42, 0x61, 0x73, 0x69, 0x63, 0x53, 0x74,
	0x75, 0x64, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x5f, 0x73, 0x74, 0x75, 0x64, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x29, 0x0a, 0x15, 0x6d, 0x67, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x79, 0x54, 0x65, 0x73, 0x74,
	0x42, 0x79, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0xac, 0x01, 0x0a, 0x16, 0x6d,
	0x67, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x79, 0x54, 0x65, 0x73, 0x74, 0x42, 0x79, 0x49, 0x44,
	0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x41, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x73, 0x74, 0x75, 0x64,
	0x79, 0x2e, 0x6d, 0x67, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x79, 0x54, 0x65, 0x73, 0x74, 0x42,
	0x79, 0x49, 0x44, 0x73, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x1a, 0x4f, 0x0a, 0x09, 0x49, 0x6e, 0x66, 0x6f,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x73,
	0x74, 0x75, 0x64, 0x79, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x79, 0x54, 0x65, 0x73, 0x74, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x67, 0x63,
	0x79, 0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x67, 0x2f, 0x42, 0x61, 0x73, 0x69, 0x63, 0x53, 0x74, 0x75,
	0x64, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69,
}

var (
	file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_rawDescOnce sync.Once
	file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_rawDescData = file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_rawDesc
)

func file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_rawDescGZIP() []byte {
	file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_rawDescOnce.Do(func() {
		file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_rawDescData)
	})
	return file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_rawDescData
}

var file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_goTypes = []interface{}{
	(*MgetStudyTestByIDsReq)(nil),  // 0: basic_study.mgetStudyTestByIDsReq
	(*MgetStudyTestByIDsData)(nil), // 1: basic_study.mgetStudyTestByIDsData
	nil,                            // 2: basic_study.mgetStudyTestByIDsData.InfoEntry
	(*StudyTest)(nil),              // 3: basic_study.studyTest
}
var file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_depIdxs = []int32{
	2, // 0: basic_study.mgetStudyTestByIDsData.info:type_name -> basic_study.mgetStudyTestByIDsData.InfoEntry
	3, // 1: basic_study.mgetStudyTestByIDsData.InfoEntry.value:type_name -> basic_study.studyTest
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() {
	file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_init()
}
func file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_init() {
	if File_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto != nil {
		return
	}
	file_github_com_yincongcyincong_BasicStudy_proto_api_basic_study_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MgetStudyTestByIDsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MgetStudyTestByIDsData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_goTypes,
		DependencyIndexes: file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_depIdxs,
		MessageInfos:      file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_msgTypes,
	}.Build()
	File_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto = out.File
	file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_rawDesc = nil
	file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_goTypes = nil
	file_github_com_yincongcyincong_BasicStudy_proto_api_test_mgetStudyTestByIDs_proto_depIdxs = nil
}
