// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.5.1
// source: github.com/yincongcyincong/BasicStudy/proto/api/question/updateStudyQuestion.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateStudyQuestionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`                                   // id
	CreateTime *uint64 `protobuf:"varint,2,opt,name=create_time,json=createTime" json:"create_time,omitempty"` // create time
	Question   *string `protobuf:"bytes,3,opt,name=question" json:"question,omitempty"`                        // question
	Answer     *string `protobuf:"bytes,4,opt,name=answer" json:"answer,omitempty"`                            // answer
	TestId     *uint64 `protobuf:"varint,5,opt,name=test_id,json=testId" json:"test_id,omitempty"`             // test
	Type       *uint32 `protobuf:"varint,6,opt,name=type" json:"type,omitempty"`                               // 1-math 2-english
}

func (x *UpdateStudyQuestionReq) Reset() {
	*x = UpdateStudyQuestionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStudyQuestionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudyQuestionReq) ProtoMessage() {}

func (x *UpdateStudyQuestionReq) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudyQuestionReq.ProtoReflect.Descriptor instead.
func (*UpdateStudyQuestionReq) Descriptor() ([]byte, []int) {
	return file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateStudyQuestionReq) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *UpdateStudyQuestionReq) GetCreateTime() uint64 {
	if x != nil && x.CreateTime != nil {
		return *x.CreateTime
	}
	return 0
}

func (x *UpdateStudyQuestionReq) GetQuestion() string {
	if x != nil && x.Question != nil {
		return *x.Question
	}
	return ""
}

func (x *UpdateStudyQuestionReq) GetAnswer() string {
	if x != nil && x.Answer != nil {
		return *x.Answer
	}
	return ""
}

func (x *UpdateStudyQuestionReq) GetTestId() uint64 {
	if x != nil && x.TestId != nil {
		return *x.TestId
	}
	return 0
}

func (x *UpdateStudyQuestionReq) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

var File_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto protoreflect.FileDescriptor

var file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_rawDesc = []byte{
	0x0a, 0x52, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x69, 0x6e,
	0x63, 0x6f, 0x6e, 0x67, 0x63, 0x79, 0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x67, 0x2f, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x53, 0x74, 0x75, 0x64, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x53, 0x74, 0x75, 0x64, 0x79, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x73, 0x74, 0x75, 0x64,
	0x79, 0x22, 0xaa, 0x01, 0x0a, 0x16, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x75, 0x64,
	0x79, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x74, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42, 0x31,
	0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x69, 0x6e,
	0x63, 0x6f, 0x6e, 0x67, 0x63, 0x79, 0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x67, 0x2f, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x53, 0x74, 0x75, 0x64, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70,
	0x69,
}

var (
	file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_rawDescOnce sync.Once
	file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_rawDescData = file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_rawDesc
)

func file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_rawDescGZIP() []byte {
	file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_rawDescOnce.Do(func() {
		file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_rawDescData)
	})
	return file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_rawDescData
}

var file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_goTypes = []interface{}{
	(*UpdateStudyQuestionReq)(nil), // 0: basic_study.updateStudyQuestionReq
}
var file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_init()
}
func file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_init() {
	if File_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStudyQuestionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_goTypes,
		DependencyIndexes: file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_depIdxs,
		MessageInfos:      file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_msgTypes,
	}.Build()
	File_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto = out.File
	file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_rawDesc = nil
	file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_goTypes = nil
	file_github_com_yincongcyincong_BasicStudy_proto_api_question_updateStudyQuestion_proto_depIdxs = nil
}
